---
version: "2"
run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m

linters:
  enable:
    # Checks for non-ASCII identifiers
    - asciicheck
    # Computes and checks the cyclomatic complexity of functions.
    - gocyclo
    # Inspects source code for security problems.
    - gosec
  settings:
    gocyclo:
      # Minimal code complexity to report.
      # https://github.com/fzipp/gocyclo#readme
      min-complexity: 28
    gosec:
      excludes:
        # Ignore controversial integer overflow warnings.
        - G115
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  # Disable max issues per linter.
  max-issues-per-linter: 0
  # Disable max same issues.
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
