---
linters:
  enable:
    # Checks for non-ASCII identifiers
    - asciicheck
    # Computes and checks the cyclomatic complexity of functions.
    - gocyclo
    # Inspects source code for security problems.
    - gosec
linters-settings:
  gosec:
    excludes:
      # Ignore the fact that we might set TLS InsecureSkipVerify
      - G402
issues:
  # Disable max issues per linter.
  max-issues-per-linter: 0
  # Disable max same issues.
  max-same-issues: 0
